### PR TITLE
add user milahu

### PR DESCRIPTION
**Pull request by milahu**
pretty please ; )

im curious how much faster this is to build qt6 than my 4x2.50GHz + 6GB laptop

via https://github.com/NixOS/nixpkgs/pull/141883#issuecomment-1021450669

### CODE REVIEW

**Comment by jonringer** [comment]
Generally I try to keep it to just committers, but looks like you've been contributing for a while

**Review by jonringer — APPROVED** [review]

**Comment by milahu** [comment]
thanks for your trust

you can reach me at `milahu@gmail.com` or `@milahu:matrix.org`

**Comment by milahu** [comment]
can you send hostname and port?

**Comment by jonringer** [comment]
emailed

**Pull request merged**
